apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pets
  template:
    metadata:
      labels:
        app: pets
    spec:
      containers:
        - name: pets
          image: whipshout/pets
          env:
            - name: MONGO_URI
              value: 'mongodb://pets-mongo-srv:27017/pets'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'iskaypet'
---
apiVersion: v1
kind: Service
metadata:
  name: pets-srv
spec:
  selector:
    app: pets
  ports:
    - name: pets
      protocol: TCP
      port: 3000
      targetPort: 3000
