name: tests-stats

on:
  pull_request:
    paths:
      - 'stats/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: cd stats && npm install && npm run test:ci
