name: tests-pets

on:
  pull_request:
    paths:
      - 'pets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd pets && npm install && npm run test:ci
